#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm test

npm --no-git-tag-version version patch
git add package.json package-lock.json
git commit -m "package version $(node -pe "require('./package.json').version")"